### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by lucax88x** [polemius/recoil-persist#5]

**Comment by bluelovers** [comment]
https://github.com/bluelovers/recoil-persist/blob/master/dist/index.d.ts

**Comment by polemius** [comment]
I have added the typescript definitions in 1.1.0 version. 
@bluelovers thank you 👍

**Comment by rhys-saldanha** [comment]
`paths` [seen here](https://github.com/polemius/recoil-persist/blob/aa55fb348e2b7f40d3931889bedfde88e263aa2d/index.d.ts#L25) is typed as a string, rather than a string array, and both parameters are not marked as optional.

The fork above seems to have done this correctly. Can I raise a PR against this issue to fix?
